export const environment = {
  production: true,
  usernameErrMsgRequire: "Username is required",
  usernameErrMsgMinLength: "Username must be greater or equal 4 character",
  usernameErrMsgMaxLength: "Username must be lesser or equal 24 character",
  passwordErrMsgRequire: "Password is required",
  firstNameErrMsgRequire: "First name is required",
  firstNameErrMsgMinLength: "First name must be greater or equal 4 character",
  firstNameErrMsgMaxLength: "First name must be lesser or equal 36 character",
  lastNameErrMsgRequire: "Last name is required",
  lastNameErrMsgMinLength: "First name must be greater or equal 4 character",
  lastNameErrMsgMaxLength: "Last name must be lesser or equal 36 character",
  phoneNumberErrMsgRequire: "Phone number is required",
  phoneNumberErrMsgInvalid: "Phone number is invalid, please use real phone number",
  emailErrMsgRequire: "Email is required",
  emailErrMsgInvalid: "Email is invalid, please use real email",
  genderErrMsgRequire: "Please choose your gender",
  accessTokenHeaderName: "Authorize",
  refreshTokenHeaderName: "Refresh-Token",
  serverUrl: "https://localhost:8080",
};
